<?php

return [
	'bitpaymagic' => [
		# https://test.bitpay.com/dashboard/merchant/api-tokens
		'pairing_code' => [
			'code'  => env( 'BITPAY_PAIRING_CODE', null ),
			'label' => env( 'BITPAY_PAIRING_CODE_LABEL', 'Pairing code label' ),
		],
		# "test" or "live", everything else will drop to defult value that is "test"
		'network'     => env( 'BITPAY_ENV', 'test' ),
		# this will be generated by command line action
		'token'       => env( 'BITPAY_GENERATED_TOKEN', null )
	]
];